---

- name: Add all locales
  template: src=locale.gen dest=/etc/locale.gen

- name: Rebuild locales database
  command: "{{ item }}"
  with_items:
    - dpkg-reconfigure locales -f noninteractive
    - /usr/sbin/locale-gen

- name: Add Zabbix Repository
  ansible.builtin.apt:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb
 
- name: Dist Upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - python3-psycopg2
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php8.2-pgsql
    - zabbix-nginx-conf 
    - zabbix-sql-scripts
    - zabbix-agent
    - postgresql
  
- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: 
    - zabbix-server
    - zabbix-agent
    - php8.2-fpm
