---

- name: Add all locales
  yum: 
    name: glibc-all-langpacks
    state: present
    update_cache: yes

- name: Add Zabbix Repository
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/9/x86_64/zabbix-release-6.0-4.el9.noarch.rpm
    state: present
    disable_gpg_check: True
 
- name: Upgrade
  ansible.builtin.yum:
    name: '*'
    state: latest
  ignore_errors: true

- name: Install packages
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - python3-psycopg2
    - zabbix-server-pgsql 
    - zabbix-web-pgsql 
    - zabbix-nginx-conf 
    - zabbix-sql-scripts 
    - zabbix-selinux-policy 
    - zabbix-agent 
    - postgresql
  
- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: 
    - zabbix-server
    - zabbix-agent
    - nginx
    - php8.2-fpm
