---

#Paylasılan dizini, olusturulan dizine mount etme
- name: Drop {{ client_ip }} ip from IPTables
  shell: "iptables -D INPUT -p tcp -s {{ client_ip }} --dport {{ item }} -j ACCEPT"
  with_items:
      - 137
      - 138
      - 139
      - 445

- name: Drop {{ client_ip }} ip from IPTables
  shell: "iptables -D OUTPUT -p tcp -d {{ client_ip }} --dport {{ item }} -j ACCEPT"
  with_items:
      - 137
      - 138
      - 139
      - 445
