---
- name: Check required variables
  fail: msg="Variable {{ item }} is not defined"
  when: item is not defined
  with_items: "{{ agent_info }}"

- name: Create a new host
  local_action:
    module: zabbix_host
    server_url: '{{ server.blitz_web_url }}'
    login_user: '{{ blitz.username }}'
    login_password: '{{ blitz.password }}'
    host_name: '{{ agent.name }}'
    visible_name: '{{ agent.name }}'
    host_groups: 
      - '{{ agent.host_groups }}'
    link_templates:
      - '{{ agent.blitz_templates }}'
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: '{{ agent.agent_ip }}'
        dns: ""
        port: '{{ blitz.blitz_monitoring_server_port }}'
