---

#Repo update etme
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes

#Nfs Server Yazılımlarını Yükleme
- name: Install nfs-server
  apt:
   name: "{{ item }}"
   state: latest
  with_items:
   - nfs-common
   - nfs-kernel-server
