---
# tasks file for plusclouds.samba.server

- name: "Check that {{ public_share_path }} exist"
  stat:
    path: "{{ public_share_path }}"
  register: public_dir_exists


- name: "Create {{ public_share_path }} directory"
  file:
    state: directory
    path: "{{ public_share_path }}"
    owner: nobody
    group: root
    mode: 0755
    recurse: yes
  when:
    - not public_dir_exists.stat.exists and public



- name: Copy the Customize {{ client_ip }}.conf file
  template:
    src: etc_samba_smb.conf.j2
    dest: /etc/samba/{{ client_ip }}.conf


- name: Set samba config file
  lineinfile:
    path: /etc/samba/smb.conf
    line: 'include = /etc/samba/{{ client_ip }}.conf'
    backup: yes
  notify:
    - Reload Samba
