mysql_service: mysql
mysql_conf_dir: /etc
mysql_port: 3306               # The port for mysql server to listen
mysql_bind_address: "0.0.0.0"  # The bind address for mysql server
mysql_root_db_pass: 12345   # The root DB password
mysql_slow_log: /var/log/mysqld-slow.log


mysql_db:                                 
  - name: test1
    replicate: yes
  - name: test2
    replicate: yes

# If the database is replicated the users
# to be used for replication:
mysql_repl_user:                          
  - name: repl
    pass: 12345

mysql_db_id: 1 #id must change on second servers
