---

#Dizin kontrolü
- name: "Check that {{ share_path }} exist"
  stat:
    path: "{{ share_path }}"
  register: public_dir_exists

#Yukarıdaki dizin yok ise dizin create eder.
- name: "Create {{ share_path }} directory"
  file:
    state: directory
    path: "{{ share_path }}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
  when: public_dir_exists.stat.exists == False

#Var olan dizini paylaşma
- name: set nfs config file
  lineinfile:
    path: /etc/exports
    line: '{{ share_path }}            {{ item }}(rw,no_root_squash,no_subtree_check,fsid=0)'
    backup: yes
  with_items:
     - "{{ client_ip }}"

- name: reload nfs server
  service: name=nfs-kernel-server state=reloaded
