---
# defaults file for plusclouds.blitz.add-host
# Aşağıdaki tüm bilgilerin girilmesi zorunludur.
# wizard = PlusClouds panelde bir web frontend page.
# Kullanıcı aşağıdaki bilgileri PlusClouds Add Host Wizardında dolduracak, api wizarddaki bilgiler ile bu rolü çalıştıracak.
blitz_host:
  server_ip: "wizarddan_gelecek_blitz_server_ip" # Agent'ın bağlanacağı monitoring server ip adresi girilir. (default: mon1.blitz.plusclouds.com)
  server_port: "wizarddan_gelecek_blitz_server_port" # Agent'ın bağlanacağı monitoring server ip adresi girilir. (default: 10050)
  web_url: "wizarddan_gelecek_blitz_web_url" # Blitz Monitoring Web URL Adresi girilir. (default: http://blitz.plusclouds.com/blitz)

# Kurulumun devamı için Plusclouds.com Paneli üzerinden oluşturduğunuz Monitoring kullanıcı bilgileri girilmelidir.
user_name: "apiden_gelecek_blitz_username"  # Plusclouds hesabınızın Blitz Monitoring Service kullanıcı adı girilir. (Api'den gelen veri)
user_pass: "apiden_gelecek_blitz_password" # Plusclouds hesabınızın Blitz Monitoring Service kullanıcı şifresi girilir. (Api'den gelen veri)

server_ip: "wizarddan_gelecek_blitz_agent_ip" # Host olarak eklenecek olan agent serverın ip adresi
server_name: "wizarddan_gelecek_blitz_agent_name" # Host olarak eklenecek olan agent isimi
host_groups: "apiden_gelecek_blitz_hostgroup" # Host olarak eklenecek agent group bilgisi (Api'den gelen veri)

# Agent'a monitoring için eklenecek olan Blitz templateleri girilir. Örneğin;
# - blitz_templates: #Hosta eklenecek olan templateler
#    - Template OS Linux
#    - Template App MySQL
#    - Template App Powerdns Server
#    - Template App Nginx
#    - Template App Galera Cluster
#    - Template Disk Performance

blitz_templates: #Hosta eklenecek olan templateler
   - "Template OS Linux"
   - "Template Disk Performance"
