stages:
  - deploy
  - scan

build_environment:
  stage: deploy
  script:
    - mkdir /home/ansible/repo -p
    - rm /home/ansible/repo/* -fR
    - rsync -ac * /home/ansible/repo

test_environment:
  stage: scan
  script:
    - su ansible
    - chmod +x update-and-test.sh
    - bash update-and-test.sh
