stages:
  - deploy
  - scan

build_environment:
  stage: deploy
  script:
    - mkdir /home/ansible/repo -p
    - cp * /home/ansible/repo -r

test_environment:
  stage: scan
  script:
    - su ansible
    - chmod +x update-and-test.sh
    - bash update-and-test.sh