stages:
  - build
#  - deploy
#  - scan

build_environment_master:
  stage: build
  tags:
    - master
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - rm /var/www/$CI_PROJECT_NAME.latest.tar.gz -f
    - tar czf /var/www/$CI_PROJECT_NAME.latest.tar.gz .
    - tar czf /var/www/$CI_PROJECT_NAME.$COMMIT_TIME.tar.gz .
  only:
    - master

build_environment_dev:
  stage: build
  tags:
    - dev
  script:
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - rm /var/www/$CI_PROJECT_NAME.latest.tar.gz -f
    - tar czf /var/www/$CI_PROJECT_NAME.latest.tar.gz .
    - tar czf /var/www/$CI_PROJECT_NAME.$COMMIT_TIME.tar.gz .
  only:
    - dev