---

- name: 'Check if grub is present'
  stat:
    path=/etc/default/grub
  register: grub_file
- name: 'Disable IPv6 - GRUB_CMD_LINE_LINUX'
  replace:
    path: /etc/default/grub
    regexp:  '^GRUB_CMDLINE_LINUX="((:?(?!ipv6\.disable=1).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 ipv6.disable=1"'
  when: grub_file.stat.exists
  register: updateGrub
- name: 'Disable IPv6 - GRUB_CMDLINE_LINUX_DEFAULT'
  replace:
    path: /etc/default/grub
    regexp:  '^GRUB_CMDLINE_LINUX_DEFAULT="((:?(?!ipv6\.disable=1).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 ipv6.disable=1"'
  register: updateGrub
  when: grub_file.stat.exists
- name: 'update-grub'
  shell: update-grub
  register: updateGrub
  when: updateGrub is defined


- name: 'sysctl disable ipv6'
  shell: 'sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && sysctl -w net.ipv6.conf.lo.disable_ipv6=1'
  register: sysctl
  when: updateGrub is defined

- name: 'sysctl disable ipv6'
  shell: 'sysctl -p'
  when: sysctl is defined
