---
- name: Run apt update
  apt:  update_cache=yes

- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Install MYsql Server and Client
  apt: pkg={{ item }} state=present update_cache=yes force=yes
  with_items:
    - mysql-server
    - mysql-client