- name: Install filebeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - filebeat

- name: Generate filebeat configuration template
  template:
    src=filebeat.yml.j2
    dest=/etc/filebeat/filebeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: filebeat_needs_restart

- name: Start filebeat service
  command: systemctl start filebeat.service
  ignore_errors: true
  become: true
  when: filebeat_needs_restart != 0

- name: Restart filebeat service
  command: systemctl restart filebeat.service
  ignore_errors: true
  become: true
  when: filebeat_needs_restart|changed

- name: Setup filebeat service
  service: name=filebeat state=started enabled=true
  become: true