- name: Install metricbeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - metricbeat

- name: Generate metricbeat configuration template
  template:
    src=metricbeat.yml.j2
    dest=/etc/metricbeat/metricbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: metricbeat_needs_restart

- name: Start metricbeat service
  command: systemctl start metricbeat.service
  ignore_errors: true
  become: true
  when: metricbeat_needs_restart != 0

- name: Restart metricbeat service
  command: systemctl restart metricbeat.service
  ignore_errors: true
  become: true
  when: metricbeat_needs_restart|changed

- name: Setup metricbeat service
  service: name=metricbeat state=started enabled=true
  become: true