- name: Install packetbeat rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - packetbeat
    - libpcap

- name: Generate packetbeat configuration template
  template:
    src=packetbeat.yml.j2
    dest=/etc/packetbeat/packetbeat.yml
    owner=root
    group=root
    mode=0644
  become: true
  register: packetbeat_needs_restart

- name: Start packetbeat service
  command: systemctl start packetbeat.service
  ignore_errors: true
  become: true
  when: packetbeat_needs_restart != 0 

- name: Restart packetbeat service
  command: systemctl restart packetbeat.service
  ignore_errors: true
  become: true
  when: packetbeat_needs_restart|changed

- name: Setup packetbeat service
  service: name=packetbeat state=started enabled=true
  become: true