---
- name: Setup php for Ubuntu 14.04 Php
  include_tasks: Ubuntu14_04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Setup php for Ubuntu 16.04 Php
  include_tasks: Ubuntu16_04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Setup php for Ubuntu 18.04 Php
  include_tasks: Ubuntu18_04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'

- name: Setup php for Debian 9
  include_tasks: Debian9.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '9.1'

- name: Setup php for CentOS 6 Php
  include_tasks: CentOS6.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- name: Setup php for CentOS 7 Php
  include_tasks: CentOS7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'