---
# Tasks file for installing docker registry

- name: Install docker and docker-compose
  package:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Create Needed Directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "/home/docker-compose/registry"
    - "/data"

- name: Copy docker-compose file
  copy:
    src: "docker-compose.yml"
    dest: /home/docker-compose/registry/docker-compose.yml
    mode: 0644

- name: Start docker-compose
  command: docker-compose up -d 
  args:
    chdir: /home/docker-compose/registry/

- name: Check if the containers are running
  command: docker ps
  register: docker_ps

- name: Display the running containers
  debug:
    var: docker_ps.stdout_lines