---
# tasks file for plusclouds.disc.extend

- name: Install dependencies
  yum:
    name: epel-release
    state: present


- name: Install dependencies(pip)
  yum:
    name: python-pip
    state: present


- name: Install Pexpect Module
  pip:
    name: pexpect

- name: "DISK | Create a partition for the added disk space"
  expect:
    command: fdisk {{ disc }}
    responses:
      'Command \(m for help\):':
        - 'd'
        - 'n'
        - 'w'
      'Select \(default.*$': 'p'
      'Partition number.*$': "{{ partition_number }}"
      'First sector.*$': "\n"
      'Last sector.*$': "\n"
    echo: yes
  ignore_errors: yes
  when: fs_type == "ext4" or "ext3"

- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0


- name: Wait for the reboot to complete.
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300


- name: "DISK | Grow the file system into the new space"
  command: xfs_growfs -d {{ disc }}{{ partition_number }}
