---
#public_share_name: public               #Public paylasılacak dosya ismi/acıklaması
#public_share_path: /samba/public        #Public paylasılacak dosya yolu, role kendi ekler
share_name: private             #Private paylasılacak dosya ismi/acıklaması
share_path: /samba/private      #Private olarak paylasılacak dosya yolu, role kendi olusturur

samba_group_name: smbgrp
samba_users:
  - name: 'fooplus'
    smbpasswd: 'pass123'


client_ip: 10.8.0.0

readonly: true                          #default olarak readonly true'dur, erişimin sadece okunabilir olmasını istiyoruz.
#public: true
#private: false
