- name: allow 3306,4567,4568,4444/tcp ports
  ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
  with_items:
    - 3306
    - 4567
    - 4568
    - 4444
- name: allow 4567/udp port
  ufw:
    rule: allow
    proto: udp
    port: 4567