---
# Maven major version number
maven_version_major: '3'
# Maven minor version number
maven_version_minor: '5'
# Maven patch version number
maven_version_patch: '2'

# Mirror where to dowload Maven redistributable package from
maven_mirror: "http://ftp.itu.edu.tr/Mirror/Apache/maven"

# SHA256 sum for the Maven redistributable package
maven_redis_sha256sum: '707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff'

# mvn binary gets symlinked into {{ maven_bin_path }}
maven_bin_path: '/usr/local/bin'
