---

- name: Delete host line in {{ item.name }} file.
  lineinfile:
    path: "{{ nginx_conf_path }}/{{ item.name }}.com.conf"
    regexp: '        server {{ item.server }};'
    state: absent
  with_items: "{{ balancer_vhosts }}"
  notify: restart nginx
