---

#Repo update
- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400


#Nfs Server Yazılımlarını Yükleme
- name: Install nfs-server
  apt:
   name: "{{ item }}"
   state: latest
  with_items:
   - nfs-common
   - nfs-kernel-server
   - nfs-server


#Servisi yeniden başlatma
- name: restart nfs server
  service: name=nfs-kernel-server state=restarted
