---

#Paylasılan dizini, olusturulan dizine mount etme
- name: Set IPTables
  shell: "iptables -A INPUT -p tcp -s {{ client_ip }} --dport {{ item }} -j ACCEPT"
  with_items:
      - 137
      - 138
      - 139
      - 445

- name: Set IPTables
  shell: "iptables -A OUTPUT -p tcp -d {{ client_ip }} --dport {{ item }} -j ACCEPT"
  with_items:
      - 137
      - 138
      - 139
      - 445
