---

- include: pre-install.yml
  when: ansible_os_family == 'Debian'

- include: setup-Java.yml
  when: ansible_os_family == 'Debian'

- include: setup-Logstash.yml
  when: ansible_os_family == 'Debian'
