---

#Paylasılan dizini, olusturulan dizine mount etme
- name: Umount extented mountpoint
  shell: "umount  {{ share_path }}"

#Disk imajını büyütme
- name: Creating File Based Disc İmages
  shell: 'dd if=/dev/zero bs={{ item.bs }} count={{ item.count }} >> {{ sg_device_dir }}/{{ item.name }}.img'
  with_items:
    - "{{ disc_infos }}"


#Paylasılan dizini, olusturulan dizine mount etme
- name: set mountpoints
  shell: "mount {{ sg_device_dir }}/{{ item.name }}.img    {{ share_path }}"
  with_items:
    - "{{ disc_infos }}"


#
- name: Umount extented mountpoint
  shell: "df -h | grep {{share_path}} | awk '{print $1}'"
  register: find_device


- name: Creating File Based Disc İmages
  shell: 'resize2fs find_device'
