---
# Install OpenResty Package Manager and OpenResty Doc
openresty_recommended_install: yes

# Packages installed for yum systems.
openresty_recommended_yum:
  - openresty-resty
  - openresty-opm
  - openresty-doc

# Protocol to be used for package download.
openresty_repo_protocol: https

centos_conf_path: /etc/openresty/
debian_conf_path: /etc/openresty/

log_path: /var/log/openresty/

openresty_user: "root"
root_group: "root"
openresty_conf_file_path: /etc/openresty/nginx.conf
debian_openresty_mime_file_path: "{{ debian_conf_path }}mime.types"
redhat_openresty_mime_file_path: "{{ centos_conf_path }}mime.types"
nginx_pidfile: /run/nginx.pid
debian_openresty_vhost_path: /etc/openresty/sites-enabled
redhat_openresty_vhost_path: /etc/openresty/sites-enabled
nginx_default_vhost_path: /etc/openresty/sites-enabled

# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "on"

nginx_error_log: "{{ log_path }}error.log warn"
nginx_access_log: "{{ log_path }}access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false


nginx_log_format: ""#|-
#  '$remote_addr - $remote_user [$time_local] "$request" '
#  '$status $body_bytes_sent "$http_referer" '
#  '"$http_user_agent" "$http_x_forwarded_for"'
