---
- name: Starting Micro Application Environment Setup
  include_tasks: "environment_micro.yml"
  when: application_type == "micro"

- name: Starting Small Application Environment Setup
  include_tasks: "environment_small.yml"
  when: application_type == "small"

- name: Starting Growing Application Environment Setup
  include_tasks: "environment_growing.yml"
  when: application_type == "growing"

- name: Starting Huge Application Environment Setup
  include_tasks: "environment_huge.yml"
  when: application_type == "huge"
