---
- name: remove ip address and save it to temp file
  raw: sed '/{{ fixed_address }}/d' mac.conf > temp.conf

- name: remove ip address and save it to temp file
  raw: mv temp.conf mac.conf

- name: restart dhcp service
  raw: service isc-dhcp-server restart