---
- name: remove ip address and save it to temp file
  raw: sed '/{{ fixed_address }}/d' /etc/dchp/mac.conf > /etc/dchp/temp.conf

- name: remove ip address and save it to temp file
  raw: mv /etc/dchp/temp.conf /etc/dchp/mac.conf

- name: restart dhcp service
  raw: service isc-dhcp-server restart