---
# tasks file for plusclouds.mysql-replication-configure

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: copy the my.cnf file
  action: template src=my.cnf.j2 dest={{ mysql_conf_dir }}/my.cnf owner=root mode=0644
  notify: restart mysql

- name: touch the mysql-slow.log file
  file: path={{ mysql_slow_log }} owner=mysql mode=0644 state=touch

- name: start mysql service
  service: name={{ mysql_service }} state=started enabled=yes

- name: create the replication users
  mysql_user: name={{ item.name }} host='%' password={{ item.pass }} priv="*.*:REPLICATION SLAVE" state=present
  with_items: '{{mysql_repl_user}}'
  when: mysql_repl_user|lower() != 'none'

- name: remove the test database
  action: mysql_db db=test state=absent

- name: create the databases
  mysql_db: name={{ item.name }} state=present
  with_items: '{{ mysql_db }}'