- name: Copy beats yum repo file
  copy:
    src=beat.repo
    dest=/etc/yum.repos.d/beat.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Creates Cert Directory
  file:
    path: /etc/beat
    state: directory
    mode: 0755

- name: Import ElasticSearch GPG Key
  rpm_key: key=http://packages.elastic.co/GPG-KEY-elasticsearch
    state=present

- name: Check ELK server SSL client certificate
  stat: path=/etc/beat/beat-forwarder.crt
  ignore_errors: true
  register: elk_client_ssl_cert_exists

- name: Install ELK server SSL client certificate
  get_url:
    url=http://{{ elk_server }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.crt
    dest=/etc/beat/beat-forwarder.crt
  become: true
  when: (elk_client_ssl_cert_exists != 0)

- name: Install ELK server SSL client certificate
  get_url:
    url=http://{{ elk_server }}:{{ elk_server_ssl_cert_port }}/beat-forwarder.key
    dest=/etc/beat/beat-forwarder.key
  become: true
  when: (elk_client_ssl_cert_exists != 0)

- name: Set Log Directory Permissions 755                  
  file:                                                         
    dest: "{{ item.path }}"                                      
    mode: 0755                                                  
    state: directory                                            
    owner: "{{ item.owner }}"                                                
    group: "{{ item.group }}"
  become: true
  with_items:
    - "{{logdirectories|default([])}}"
  
                                                                
- name: Set Log File Permissions 644                      
  command: find "{{ item.path }}" -type f -exec chmod 0644 {} \;   
  become: true
  with_items:
    - "{{logdirectories|default([])}}"