---
- name: add GitLab package repository
  shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh | sudo bash
  args:
    creates: /etc/apt/sources.list.d/runner_gitlab-ci-multi-runner.list

- name: install packages
  apt:
    pkg:
      - gitlab-ci-multi-runner
    state: present

- name: Check if gitlab runner is already registered
  command: /usr/bin/gitlab-runner verify
  become: yes
  become_method: sudo
  register: gitlab_registration
  ignore_errors: yes

- name: configure GitLab Runner
  template:
    src: config.toml
    dest: /etc/gitlab-runner/config.toml
    owner: root
    group: root
    mode: 0600
  become: yes
  become_method: sudo
  when: ('is alive' not in gitlab_registration.stderr)

- name: register GitLab Runner
  command: |
    /usr/bin/gitlab-runner register \
      --non-interactive \
      --url "{{ gitlab_url }}" \
      --registration-token {{ runner_token }} \
      --tag-list {{ runner_tags }} \
      --name {{runner_name}} \
      --limit {{runner_limit}} \
      --executor {{ runner_executor }} \
      --machine-idle-nodes {{runner_idle_nodes}} \
      --machine-idle-time {{runner_idle_time}} \
      --machine-max-builds {{runner_max_builds}}
  become: yes
  become_method: sudo
  when: ('is alive' not in gitlab_registration.stderr)
