---
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart spring application
  become: yes
  service: name={{spring_service_name}} state=restarted enabled=yes
  register: spring_app_restarted
