---
- name: Check if Proxy Config Exists
  stat: path=/etc/nginx/sites-enabled/{{ domain_name }}.conf
  register: proxy_config

- name: Create Proxy Config
  template: src=proxy_conf.j2 dest=/etc/nginx/sites-enabled/{{ domain_name }}.conf owner=root group=root mode=0600
  when: proxy_config.stat.exists == False
  notify: Reload Nginx

- name: Proxy Config Status
  debug:
    msg: "Proxy Config exist for this domain. If you want to make changes set Action to Update"
  when: proxy_config.stat.exists == True