---
---
- name: Check if Nginx Exists
  stat: path=/etc/init.d/nginx
  register: service_status

- name: Nginx Status
  debug:
    msg: "Skipping nginx installation. Nginx is already exist."
  when: proxy_config.stat.exists == True

- name: Include Installation
  include_tasks: nginx-install.yml
  when: service_status.stat.exists == False
  
- name: Include Ubuntu 14.04 installation
  include_tasks: ubuntu-14.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
  
- name: Include Ubuntu 16.04 installation
  include_tasks: ubuntu-16.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Include Ubuntu 18.04 installation
  include_tasks: ubuntu-18.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
