- name: Copy script to /usr/local/bin/
  copy: 
    src: lld-disks.py
    dest: /usr/local/bin/lld-disks.py
    owner: root
    group: root
    mode: 0777

- name: Copy config to zabbix-agent.d
  copy: 
    src: userparameter_diskstats.conf
    dest: /etc/zabbix/zabbix-agent.d/userparameter_diskstats.conf
  notify: restart zabbix-agent
