- name: add settings to sudo config
  blockinfile:
    path: /etc/sudoers
    block: |
      # Zabbix Agent PDNS
      Defaults:zabbix !requiretty
      zabbix ALL=NOPASSWD: /usr/bin/pdns_control

- name: Copy config to zabbix-agent.d
  copy: 
    src: pdns.conf
    dest: /etc/zabbix/zabbix-agent.d/pdns.conf
  notify: restart zabbix-agent