---
- name: Create Apache Kafka input topic.
  shell: /usr/local/kafka_2.12-2.3.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic {{ item }}
  with_items: '{{ input_topic_name }}'

- name: Create Apache Kafka output topic.
  shell: /usr/local/kafka_2.12-2.3.0/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic {{ item }}
  with_items: '{{ output_topic_name }}'
