---
# tasks file for plusclouds-mysql-backup
name: installing xtrabackup for ubuntu
  apt:
    deb: https://www.percona.com/downloads/XtraBackup/Percona-XtraBackup-2.4.4/binary/debian/jessie/x86_64/percona-xtrabackup-24_2.4.4-1.jessie_amd64.deb

name: Creates script directory
  file:
    path: {{script-path}}
    state: directory

name: Creates backup directory
  file:
    path: {{backup-path}}
    state: directory

name: Creates daily backup cronjob
  cron: 
    minute: '0' 
    hour: '2' 
    name: 'Backup mysql(daily schedule)'
    cron_file: 'mysql-daily-backup'
    user: 'root'
    job: 'bash {{script_path}}/incremental-mysql-backup.sh backup > /dev/null'

name: Download script file
  get_url:
    url: https://raw.githubusercontent.com/dereliahmet1/scripts/dereliahmet1/incremental-mysql-backup.sh
    dest: {{script-path}}
    mode: 0777
name: edit script
 replace:
    path: {{script-path}}/incremental-mysql-backup.sh
    regexp: 'backup-path'
    replace: '{{backup-path}}'
    backup: yes
name: editscript
 replace:
    path: {{script-path}}/incremental-mysql-backup.sh
    regexp: 'username'
    replace: '{{mysql-user-name}}'
    backup: yes
name: editscriptp
 replace:
    path: {{script-path}}/incremental-mysql-backup.sh
    regexp: 'password'
    replace: '{{mysql-user-password}}'
    backup: yes  
name: editscriptt
 replace:
    path: {{script-path}}/incremental-mysql-backup.sh
    regexp: 'mysqlcfg-path'
    replace: '{{mysql-config-path}}'
    backup: yes
name: editscripts
 replace:
    path: {{script-path}}/incremental-mysql-backup.sh
    regexp: 'mysqldata-path'
    replace: '{{mysql-data-path}}'
    backup: yes

name: run script for backup
  shell: "bash {{script-path}}/incremental-mysql-backup.sh backup"
