---
# tasks file for plusclouds.zabbix-mysql-install
- name: Create Zabbix DB File
  copy: src=create.sql.gz dest=/home owner=root group=root mode=0600

- name: install python mysql bindings
  apt: 
    name: python-mysqldb 
    state: present

- name: Change MySQL root password
  mysql_user: name=root host={{ item }} password={{ DB_Password }}
  with_items:
    - 127.0.0.1 
    - ::1
    - localhost

- name: Create my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Create MySQL DB
  mysql_db: name={{DB_Name}} state=present
  register: create_db

- name: Import MySQL structure
  mysql_db: name={{DB_Name}} state=import target=/home/create.sql.gz

- name: Grant privileges to MySQL DB
  mysql_user: name={{DB_Name}} password={{DB_Password}} priv={{DB_Name}}.*:ALL state=present
