---
- name: Add apt key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
  register: import_key

- name: Add Ubuntu apt repository
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- debug: msg="{{ansible_distribution}}"

- name: Add Debian apt repository
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} openresty"
    state: present
  when: ansible_distribution == 'Debian'

- name: Install OpenResty
  apt:
    name: openresty
    state: present
    update_cache: yes
    install_recommends: "{{ openresty_recommended_install }}"
  notify: restart openresty

#Dizin kontrolü
- name: "Check that {{ debian_conf_path }} exist"
  stat:
    path: "{{ centos_conf_path }}"
  register: conf_path_dir_exists

#Yukarıdaki dizin yok ise dizin create eder.
- name: "Create {{ debian_conf_path }} directory"
  file:
    state: directory
    path: "{{ debian_conf_path }}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
  when: conf_path_dir_exists.stat.exists == False

- name: Copy the Customize nginx.conf file
  template:
    src: nginx.conf.j2
    dest: /etc/openresty/nginx.conf
