---
- name: Add apt key
  apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
  register: import_key

- name: Add Ubuntu apt repository
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} main"
    state: present
  when: ansible_distribution == 'Ubuntu'

- debug: msg="{{ansible_distribution}}"

- name: Add Debian apt repository
  apt_repository:
    repo: "deb http://openresty.org/package/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} openresty"
    state: present
  when: ansible_distribution == 'Debian'

- name: Install OpenResty
  apt:
    name: openresty
    state: present
    update_cache: yes
    install_recommends: "{{ openresty_recommended_install }}"
  notify: restart openresty

- name: "Create {{ debian_conf_path }} and {{ log_path }} directory"
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
  with_items:
     - "{{ debian_openresty_vhost_path }}"
     - "{{ log_path }}"

- name: "Create log file"
  file:
    state: touch
    path: "{{ item }}"
    owner: "{{ openresty_user }}"
  with_items:
     - "{{ log_path }}error.log"
     - "{{ log_path }}access.log"

- name: Copy the Customize nginx.conf file
  template:
    src: nginx.conf.j2
    dest: /etc/openresty/nginx.conf
