- name: Install utilities spring
  package: name={{ item }} state=present
  with_items:
    - unzip

- name: Unzip demo application
  unarchive:
    src: spring-app.zip
    dest: /var


- name: Create Spring Application group
  group: name={{spring_application_group}}
         state=present
         system=yes

- name: Create Spring Application user
  user: name={{spring_application_user}}
        group={{spring_application_group}}
        system=yes
        shell=/sbin/nologin
        createhome=no
        home=/var/app

- name: Set Spring Application Directory Permissions 755
  file:
    dest: "{{spring_application_path}}"
    mode: 0755
    state: directory
    owner: "{{spring_application_user}}"
    group: "{{spring_application_group}}"
    recurse: true
  become: true

- name: Set Spring Application Log Directory Permissions 755
  file:
    dest: "{{spring_application_path}}/log"
    mode: 0755
    state: directory
    owner: "{{spring_application_user}}"
    group: "{{spring_application_group}}"
    recurse: true
  become: true

- name: Set Spring Application File Permissions
  command: find {{ spring_application_path }} -type f -exec chmod 0644 {} \;

- name: Copy Systemd File for Instance
  become: yes
  template: src=spring.systemd.j2 dest={{systemd_path}}/{{spring_service_name}}.service mode=0644 force=yes
  notify:
  - reload systemd configuration
  - restart spring application
