

- name: Update repo cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

- name:  Add gpg key
  shell : curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

- name: Add repository
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"

- name: Install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

