---
# tasks file for plusclouds.nginx.proxy_manager.setup

- name: Debian 10 apt fix
  shell: apt update --allow-releaseinfo-change

- name: Install docker
  include_tasks: docker_install.yaml

- name: Install docker compose
  include_tasks: docker_compose_install.yaml

- name: Make sure folder_path exists
  file:
    path: "{{folder_path}}"
    state: directory

- name: Place the default template
  template:
    src: docker-compose.j2
    dest: "{{folder_path}}docker-compose.yaml"