- name: Create random password for root
  uri:
    url: "https://api.plusclouds.com/v2/generator/password?length=12"
    method: GET
    return_content: yes
    status_code: 200, 404
    timeout: 20
  register: mysql_password

- name: Set mysql root password
  set_fact:
    mysql_root_password: "{{mysql_password.json.data.password}}"

- name: Create random password for npm
  uri:
    url: "https://api.plusclouds.com/v2/generator/password?length=12"
    method: GET
    return_content: yes
    status_code: 200, 404
    timeout: 20
  register: mysql_password

- name: Set mysql npm password
  set_fact:
    mysql_npm_password: "{{mysql_password.json.data.password}}"