- name: Login and get the token
  uri:
    url: "http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:{{proxy_manager_port}}/api/tokens"  
    body:
      identity: admin@example.com
      secret: changeme
    method: POST
    body_format: json
    return_content: yes
    status_code: 200
    timeout: 15
  register: user_token
  delegate_to: localhost
  until: user_token.status == 200
  retries: 15 
  delay: 3

- debug:
    msg: "{{user_token}}"
  delegate_to: localhost

- name: Change email, name and nickname
  uri:
    url: "http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:{{proxy_manager_port}}/api/users/1"
    body:
      name: "UserRealName"
      nickname: "{{proxy_manager_user_name}}"
      email: "{{proxy_manager_user_email}}"
      roles: ["admin"]
      is_disabled: false
    method: PUT
    body_format: json
    headers:
      Authorization: "Bearer {{ user_token.json.token }}"
    return_content: yes
    status_code: 200
    timeout: 15
  register: change_output
  delegate_to: localhost

- debug:
    msg: "{{change_output}}"
  delegate_to: localhost

- name: change
  uri:
    url: "http://{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}:{{proxy_manager_port}}/api/users/1/auth"
    body:
      type: "password"
      current: "changeme"
      secret: "{{proxy_manager_user_password}}"
      roles: ["admin"]
      is_disabled: false
    method: PUT
    body_format: json
    headers:
      Authorization: "Bearer {{ user_token.json.token }}"
    return_content: yes
    status_code: 201
    timeout: 15
  register: change_output
  delegate_to: localhost

- debug:
    msg: "{{change_output}}"
  delegate_to: localhost