---

- name: Setup Ubuntu 14.04 Php
  include_tasks: Ubuntu14.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'


- name: Setup Ubuntu 16.04 Php
  include_tasks: Ubuntu16.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'


- name: Setup Ubuntu 18.04 Php
  include_tasks: Ubuntu18.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'


- name: Setup CentOS 6 Php
  include_tasks: CentOS6.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'


- name: Setup CentOS 7 Php
  include_tasks: CentOS7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'


- name: Setup Debian 9
  include_tasks: debian9.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '9'

- name: Setup Debian 10
  include_tasks: debian10.yml
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'
