---

- name: configure poller logstash
  template:
    src: logstash-poller.conf.j2
    dest: /etc/logstash/conf.d/{{incoming_ip}}.conf

- name: configure poller logstash
  template:
    src: logstash-output.conf.j2
    dest: /etc/logstash/conf.d/output.conf
