# tasks file for plusclouds.matomo.apache.install
- name: Update the system
  command: apt-get update
  become: yes


- name: Install apache server
  apt:
    name: apache2
    state: present
  become: yes
