---
  - name: Ubuntu 14.04 trusty install percona xtrabackup 2.4.9.
    include_tasks: ubuntu_trusty.yml
    when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty'

  - name: Creates script directory {{ script_path }}
    file: path={{ script_path }} state=directory

  - name: Creates backup directory
    file: path={{backup_path}} state=directory

  - name: Creates daily backup cronjob if true
    cron:
      minute: '{{ cron_minute }}'
      hour: '{{ cron_hour }}'
      day: '{{ cron_day }}'
      month: '{{ cron_month }}'
      name: 'Backup mysql(daily schedule)'
      cron_file: 'mysql-daily-backup'
      user: 'root'
      job: 'bash {{ script_path }}/incremental-mysql-backup.sh backup > /dev/null'
    when: cron_status == True


  - name: Copy script file
    template:
      src: 'incremental-mysql-backup.j2'
      dest: '{{ script_path }}/incremental-mysql-backup.sh'
      mode: 0777

  - name: run script for backup
    shell: "bash {{ script_path }}/incremental-mysql-backup.sh backup"
