---
- name: os-specific vars
  include_vars: "{{ansible_os_family}}.yml"
      
- include: install.yml

- include: configure-master.yml
  when: nodetype == "master"

- include: users.yml
  when: nodetype == "master"

- include: databases.yml
  when: nodetype == "master"

- include: configure-slaves.yml
  when: nodetype == "slaves"
