- name: Set users
  set_fact: users=[]
  when: users is not defined

- name: Add default users
  include_vars: users.yml
  when: add_default_users

- name: Merge users
  set_fact:
    users: "{{ users }} + {{ users_db }}"
  when: add_default_users

# List Users
- name: List Users
  debug: msg=""
  with_items:
    - "{{ users }}"
