---
- name: Check required variables
  fail: msg="Variable {{ item }} is not defined"
  when: item is not defined
  with_items: "{{ agent_server }}"

- name: Create a new host
  local_action:
    module: zabbix_host
    server_url: '{{ blitz_host.web_url }}'
    login_user: '{{ blitz_user.user_name }}'
    login_password: '{{ blitz_user.user_pass }}'
    host_name: '{{ agent_server.agent_name }}'
    visible_name: '{{ agent_server.agent_name }}'
    host_groups: 
      - '{{ agent_server.host_groups }}'
    link_templates:
      - '{{ agent_server.blitz_templates }}'
    status: enabled
    state: present
    inventory_mode: automatic
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: '{{ agent_server.server_ip }}'
        dns: ""
        port: '{{ blitz_host.server_port }}'
