---

#Exports dosyasından paylaşılan ip'yi kaldırma

- name: set nfs config file
  lineinfile:
    path: /etc/exports
    state: absent
    regexp: "{{ share_path }}            {{ client_ip }}"
    backup: yes



- name: reload nfs server
  service: name=nfs-kernel-server state=reloaded
