---
- name: Set Disk 0
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_data.json.data.id }}/set-disk
    method: PUT
    headers:
      Authorization: "{{ user_token }}"
    body: "device=0&size={{ disk0_size }}&auto_attach={{ disk0_attached }}&storage_volume_ref={{ disk0_storage_volume }}"
    status_code: 204
  when: vm_data is success and disk0_exists == 1

- name: Set Disk 1
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_data.json.data.id }}/set-disk
    method: PUT
    headers:
      Authorization: "{{ user_token }}"
    body: "device=1&size={{ disk1_size }}&auto_attach={{ disk1_attached }}&storage_volume_ref={{ disk1_storage_volume }}"
    status_code: 204
  when: vm_data is success and disk1_exists == 1

- name: Set Disk 2
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_data.json.data.id }}/set-disk
    method: PUT
    headers:
      Authorization: "{{ user_token }}"
    body: "device=2&size={{ disk2_size }}&auto_attach={{ disk2_attached }}&storage_volume_ref={{ disk2_storage_volume }}"
    status_code: 204
  when: vm_data is success and disk2_exists == 1

- name: Set Disk 3
  uri:
    url: http://apiv2/v2/iaas/virtual-machines/{{ vm_data.json.data.id }}/set-disk
    method: PUT
    headers:
      Authorization: "{{ user_token }}"
    body: "device=3&size={{ disk3_size }}&auto_attach={{ disk3_attached }}&storage_volume_ref={{ disk3_storage_volume }}"
    status_code: 204
  when: vm_data is success and disk3_exists == 1