  ---
# tasks file for plusclouds.datebase.mysql.user.add
- name: Update Package and Install python-mysqldb and python-pycurl
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - python-pycurl
    - python-mysqldb
    
- name: Create my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Create a database user
  mysql_user: name={{ user_name }} password={{ user_password }} priv={{ user_privilages }} host={{ user_host }}
