---
# SEARCHING FOR MAC ADDRESS OF IP ADDRESS

- name: Search for mac address of related ip
  shell: arping -c 1 {{ ip }} | grep from | awk {'print$4'} | sort -u
  register: mac_address
  ignore_errors: yes

- set_fact:
     macs: "{{ mac_address.results | map(attribute='stdout') | list }}"

- set_fact:
    host_network_info: "{{ host_network_info | default([]) + [dict(mac=item[0], ip=item[1])] }}"
  loop: "{{ macs | zip(ip_addr) | list }}"

- name: Store ip address as reserved
  uri:
    url: http://{{leo_url}}/v2/packetbender/ip/set-mac-and-ip
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "allow=1&auto_configuration=0&ip_addr={{ item.ip }}&mac_addr={{ item.mac }}"
    return_content: yes
    status_code: 201
    timeout: 300
  with_items: "{{ host_network_info }}"
  delegate_to: localhost
  ignore_errors: yes