---

#Nfs Server Yazılımlarını Yükleme
- name: Install nfs-server
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
   - nfs-utils
   - libselinux-python

- name: set firewalld
  shell: "firewall-cmd --permanent --zone=public --add-service=nfs"

- name: set firewalld
  shell: "firewall-cmd --permanent --zone=public --add-service=mountd"

- name: set firewalld
  shell: "firewall-cmd --permanent --zone=public --add-service=rpc-bind"

#Firewall ayarlarını yeniden yükleme
- name: Bounce firewalld
  service: name=firewalld state=reloaded

#Servisi yeniden başlatma
- name: restart nfs server
  service: name=nfs-server state=reloaded
