---
- name: Create defauls network pool if Cloud Node does not have any
  uri:
    url: "{{ leo_url }}/v2/iaas/network-pools"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "\
name={{ datacenter_node.name }} Network&\
management_type=api&\
ip_addr={{ compute_pool.master_ip_addr }}&\
management_url={{ compute_pool.management_url }}&\
port=443&\
username={{ compute_pool.username }}&\
password={{ compute_pool.password }}&\
is_active=1&\
datacenter_ref={{ datacenter_node.datacenter.data.id }}"
    return_content: yes
    status_code: 201
    timeout: 300
  register: network_pool
