---
- name: Create default storage pool if Cloud Node does not have any
  uri:
    url: "{{ leo_url }}/v2/iaas/storage-pools"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "\
name={{ datacenter_node.name }} Storage&\
currency_code={{ compute_pool.currency_code }}&\
hourly_price={{ compute_pool.hdd_hourly_price }}&\
ip_addr={{ compute_pool.master_ip_addr }}&\
username={{ compute_pool.username }}&\
password={{ compute_pool.password }}&\
is_active=1&\
connection_type=local&\
datacenter_ref={{ datacenter_node.datacenter.data.id }}"
    return_content: yes
    status_code: 201
    timeout: 300
  register: storage_pool
