---
- name: Sync. Compute Members
  uri:
    url: http://apiv2/v2/iaas/cron/sync/compute-members
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "compute_pool_ref={{ compute_pool.json.data.0.id }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20

- name: Sync. Storage Volumes
  uri:
    url: http://apiv2/v2/iaas/cron/sync/storage-volumes
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "compute_pool_ref={{ compute_pool.json.data.0.id }}&storage_pool_ref={{ storage_pool.json.data.id }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20

- name: Sync. Networks
  uri:
    url: http://apiv2/v2/iaas/cron/sync/networks
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "compute_pool_ref={{ compute_pool.json.data.0.id }}&network_pool_ref={{ network_pool.json.data.id }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20