---
- name: Get Cloud Node Information
  uri:
    url: http://apiv2/v2/iaas/datacenter-nodes?include=datacenter&slug={{ datacenter_node_slug }}
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: datacenter_node

- name: Check if datacenter node has compute pool
  uri:
    url: http://apiv2/v2/iaas/compute-pools?datacenterNode={{ datacenter_node.json.data.0.id }}&fields=username,password,master_ip_addr,management_url
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: compute_pool
  ignore_errors: true

- name: Check if datacenter node has storage pool
  uri:
    url: http://apiv2/v2/iaas/storage-pools?datacenterNode={{ datacenter_node.json.data.0.id }}
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200, 404
    timeout: 300
  register: storage_pool
  ignore_errors: true

- name: Include create storage pool
  include_tasks: "create_default_storage_pool.yml"
  when: storage_pool.status == 404

- name: Check if datacenter node has network pool
  uri:
    url: http://apiv2/v2/iaas/network-pools?datacenterNode={{ datacenter_node.json.data.0.id }}
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200, 404
    timeout: 300
  register: network_pool
  ignore_errors: true

- name: Include create default network pool
  include_tasks: "create_default_network_pool.yml"
  when: network_pool.status == 404