---
- name: Sync. Virtual Machines
  uri:
    url: "{{leo_url}}/v2/iaas/cron/sync/virtual-machines"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "datacenter_node_ref={{ datacenter_node.id }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20

- name: Sync. Virtual Disk Images
  uri:
    url: "{{leo_url}}/v2/iaas/cron/sync/virtual-disk-images"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "datacenter_node_ref={{ datacenter_node.id }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: sleep for 20 seconds and continue with play
  wait_for:
    timeout: 20

- name: Sync. Virtual Network Cards
  uri:
    url: "{{leo_url}}/v2/iaas/cron/sync/virtual-network-cards"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "datacenter_node_ref={{ datacenter_node.id }}"
    return_content: yes
    status_code: 204
    timeout: 300