---

- name: Repo Update
  become: true
  apt:
    update_cache: yes


- name: Install server properties
  become: yes
  apt: name=software-properties-common state=latest


- name: Install the PHP Repository
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present


- name: Repo update
  become: true
  apt:
    update_cache: yes

- name: Install PHP7.2-FPM
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ ubuntu18_php_pkgs }}"
