---
- name: Import Task File
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
    
- name: Nginx | Vhosts copy
  template: src=vhosts.j2 dest=/etc/nginx/sites-enabled/{{ item.name }}.conf
  with_items: "{{balancer_vhosts}}"
  notify: restart nginx

- name: Enable init.d
  service:
    name: nginx
    state: started
    enabled: yes
