---
- name: cole vm
  hosts: all

  vars:
    user_token: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjFhYzBhY2U0YTJhYWI2Mjg2Y2M4NDY2ZTExMjRjNmQ0YzIyNGE5NzljYzU3NzZmY2Q2MGI4N2QwYzE4MDQxZmU1OTE0ZDJlYmQ2MzdiN2Y2In0.eyJhdWQiOiIyIiwianRpIjoiMWFjMGFjZTRhMmFhYjYyODZjYzg0NjZlMTEyNGM2ZDRjMjI0YTk3OWNjNTc3NmZjZDYwYjg3ZDBjMTgwNDFmZTU5MTRkMmViZDYzN2I3ZjYiLCJpYXQiOjE1MzgzOTAyNDQsIm5iZiI6MTUzODM5MDI0NCwiZXhwIjoxNTY5OTI2MjQ0LCJzdWIiOiIxMTU2OSIsInNjb3BlcyI6W119.o06Q7kIACpR3WHwskkH2ucRmahOKjYjAbMH_tgjlYvpEKQXDLD_yfeHmHTQqXOLs3HZRCox2uYybUjLurvOVz_EhUp_JPiBdOZlNQevWdDN6VV85cvweWw0adu5RLmcH6Nx2K_SM1ed9Rs2ZydOY3SW4tSdhUPMAl9wzpv4XuwWhesa1SnnrOETKzZBeq_tcQ8Lsak0NM2KZ0ip6mr9bYB2MvaMH6GfAcorCsYNSQR4hh84SjeXqYRMEob71Dq5VX5n8ssuDGyURtmj81DS7ztlchYgudw0NVPpx3Y0_SaUa5AE_uiF0-r-oB7ad9KMkcMzjRLfVrAFnAqjjdiKESC4zY1Eyhc1CQQcU92vmk4tphACc9CNspKmFw5lvpZO7uzPJqRAkco0KiBwkhbYKBdmS0QWvfCNxL6A_2NI219QtkRdZslcgTDoijvoDlXi0TOCk89CG7oohxa9rJf-sZsIyzYIseMPKRU2AkCgSaI6jlxruAYnPj3EF6QOq49Ghi3ocUKBDaVfR6jFP86II0dAnTej7QmATsw10VzOZVC_91AL42l2p3Pdf5dsJE2W3NhhQMiVGc5udPxteWsqEhn-L2EnA8fOyX_iStZUy200oxao5fQRuoVmlKqY-PoZPxiv29Ch4yBdEcYh0hz5yes01KrTPbJs9t3DaDx22cXQ"
    template_vm: "nMkLOWLqWw"
    vm_name: "CcC Baris Baskan CcC"
    total_cpu: 1
    total_ram: 512
    datacenter_node_ref: "yVMNlGrzlo"

  tasks:
    - name: Clone VM
      uri:
        url: http://apiv2/v2/iaas/virtual-machines/{{ template_vm }}/clone
        method: POST
        headers:
          Authorization: "{{ user_token }}"
        body: "name={{ vm_name }}&total_cpu={{ total_cpu }}&total_ram={{ total_ram }}&datacenter_node_ref={{ datacenter_node_ref }}"
        return_content: yes
        status_code: 201
      register: cloned_vm_data

    - name: Post Cloned VM Data
      debug:
        var: cloned_vm_data.json.data

    - name: Get VM Network Card
      uri:
        url: http://apiv2/v2/iaas/virtual-network-cards?virtual_machine={{ cloned_vm_data.json.data.id }}
        headers:
          Authorization: "{{ user_token }}"
        return_content: yes
        status_code: 200
      register: vm_network

    - name: Post VM Network Data
      debug:
        var: item.name
      loop: "{{ vm_network.json.data }}"

    # - name: start vm
    #   uri:
    #     url: http://apiv2/v2/iaas/virtual-machines/{{ cloned_vm_data.json.data.id }}/start
    #     method: PUT
    #     headers:
    #       Authorization: "{{ user_token }}"
    #     return_content: yes
    #     status_code: 201
    #   register: webpage
