---
user_token: ""
datacenter_node_ref: "yVMNlGrzlo"
template_vm: "bERLzGrvaZ"
vm_name: "New Virtual Machine"
total_cpu: 8
total_ram: 1024
do_network_conf: True

disk0_exists: 1
disk0_storage_volume: "vyGLGyNoWk"
disk0_size: 10000
disk0_attached: 1
disk1_exists: 0
disk1_storage_volume: "vyGLGyNoWk"
disk1_size: 0
disk1_attached: 0
disk2_exists: 0"
disk2_storage_volume: "vyGLGyNoWk"
disk2_size: 0
disk2_attached: 0
disk3_exists: 0
disk3_storage_volume: "vyGLGyNoWk"
disk3_size: 0
disk3_attached: 0
disk4_exists: 0
disk4_storage_volume: "vyGLGyNoWk"
disk4_size: 0
disk4_attached: 0
disk5_exists: 0
disk5_storage_volume: "vyGLGyNoWk"
disk5_size: 0
disk5_attached: 0
disk6_exists: 0
disk6_storage_volume: "vyGLGyNoWk"
disk6_size: 0
disk6_attached: 0
disk7_exists: 0
disk7_storage_volume: "vyGLGyNoWk"
disk7_size: 0
disk7_attached: 0

vif0_exists: 1
vif0_network: "vyGLGyNoWk"
vif0_assign_ip: 1
vif0_ip: "10.8.244.254"
vif0_do_network_conf: 1
vif1_exists: 0
vif1_network: ""
vif1_assign_ip: 1
vif1_ip: ""
vif1_do_network_conf: 1
vif2_exists: 0
vif2_network: ""
vif2_assign_ip: 1
vif2_ip: ""
vif2_do_network_conf: 1
vif3_exists: 0
vif3_network: ""
vif3_assign_ip: 1
vif3_ip: ""
vif3_do_network_conf: 1
vif4_exists: 0
vif4_network: ""
vif4_assign_ip: 1
vif4_ip: ""
vif4_do_network_conf: 1
vif5_exists: 0
vif5_network: ""
vif5_assign_ip: 1
vif5_ip: ""
vif5_do_network_conf: 1
vif6_exists: 0
vif6_network: ""
vif6_assign_ip: 1
vif6_ip: ""
vif6_do_network_conf: 1