---

#Paylasılan dizini, olusturulan dizine mount etme
- name: set mountpoints
  shell: "umount  {{ local_mount_path }}"


#Fstab dosyasından bağlanılan ip'yi kaldırma
- name: set nfs config file
  lineinfile:
    path: /etc/fstab
    regexp: "{{ host_ip }}:{{ host_share_path }}   {{ local_mount_path }}"
    state: absent
    backup: yes
