---
- name: Create Proxy Config
  template: src=proxy_conf.j2 dest=/etc/nginx/sites-enabled/{{ domain_name }}.conf owner=root group=root mode=0600
  notify: Reload Nginx
- name: Proxy Config Status
  debug:
    msg: "Proxy Config Updated"