---
- name: Include Ubuntu 14.04 installation
  include_tasks: ubuntu-14.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
  
- name: Include Ubuntu 16.04 installation
  include_tasks: ubuntu-16.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Include Ubuntu 18.04 installation
  include_tasks: ubuntu-18.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
