---
- name: install zabbix-agent 3.0 rpm repo
  yum:
    name: http://repo.zabbix.com/zabbix/3.0/rhel/6/x86_64/zabbix-agent-3.0.15-1.el6.x86_64.rpm
    state: present
    
- name: Copy config zabbix-agentd.conf 
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent