---
- name: Install zabbix3 Repository
  apt: deb=http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+trusty_all.deb state=present

- name: update_cache
  apt:
    update_cache: yes

- name: Install packages
  apt: 
    name: '{{ item }}'
    state: present
  with_items:
    - software-properties-common
    - zabbix-agent

- name: Copy config zabbix-agentd.conf 
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent