---
- name: Check required variables
  fail: msg="Variable {{ item }} is not defined"
  when: item is not defined
  with_items: "{{ blitz_server_bilgileri }}"

- name: Check required variables
  fail: msg="Variable {{ item }} is not defined"
  when:  item is not defined
  with_items: "{{ blitz_server_bilgileri }}"

- name: Debian zabbix-agent install 
  include_tasks: Debian.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Debian zabbix-agent install 
  include_tasks: CentOS6.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6'

- name: Debian zabbix-agent install 
  include_tasks: CentOS7.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'

- name: Debian zabbix-agent install 
  include_tasks: Debian.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Firewall configuration 
  include_tasks: applyfirewall.yml
  when: apply_firewall_rules

- name: Disk Monitoring
  include_tasks: diskmon.yml
  when: disk_performance_monitoring

- name: Galera Monitoring
  include_tasks: galeramon.yml
  when: galera_monitoring

- name: Nginx Monitoring
  include_tasks: diskmon.yml
  when: nginx_monitoring
   
- name: Mysql Monitoring
  include_tasks: mysqlmon.yml
  when: mysql_monitoring 

- name: Pdns Monitoring
  include_tasks: pdnsmon.yml
  when: powerdns_montoring

- name: Add host to blitz server
  include_tasks: addhost.yml
  when: host_ekle