- name: Allow release info change
  lineinfile:
    path: /etc/apt/apt.conf.d/99releaseinfochange
    state: present
    create: yes
    line: Acquire::AllowReleaseInfoChange::Suite "true";

- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes

- name: Check if a reboot is needed on server
  register: reboot_required_file
  stat: path=/var/run/reboot-required get_md5=no

- name: Reboot the box if kernel updated
  reboot:
    msg: "Reboot initiated by Ansible for kernel update"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    test_command: uptime
  when: reboot_required_file.stat.exists
