- name: Allow release info change update
  shell: apt-get --allow-releaseinfo-change update

- name: Update cache and upgrade if specified.
  become: true
  apt:
    update_cache: yes
    upgrade: "{{upgrade}}"