# Datadog settings
datadog_api_key: "{{ datadog_key }}"
datadog_agent_version: "5.19.0-1"
datadog_checks:
  process:
    init_config:
    instances:
      - name: ssh
        search_string: ['ssh', 'sshd' ]
      - name: rsyslog
        search_string: ['rsyslogd' ]
        cpu_check_interval: 0.2
        exact_match: true
  postgres:
    init_config:
    instances:
      - host: localhost
        port: 5432
        username: "{{postgresql_admin}}"
        password: "{{postgresql_admin_password}}"
        tags:
          - postgresql:{{ __environment }}