---
- hosts: samba-server
  roles:
    - plusclouds.samba.server
    - plusclouds.samba.server
    - plusclouds.samba.server.adduser
    - plusclouds.samba.server.mount
    - plusclouds.samba.add.client.iptables.rule
  vars:
    - samba_group_name: sambagroup       #Storage servera login olabilmek için oluşturulacak kullanıcı grubu.
    - samba_users:
      - name: plusclouds                 #Paylaşım yapılacak usr'in ismi
        smbpasswd: pass123               #Paylaşım yapılacak usr'in parolası
    - share_name: deneme1                #Paylaşılan dizinin ismi/açıklaması
    - share_path: /home/deneme
    - client_ip: 10.8.0.1                #Paylaşıma açılacak client ip'si.
    - readonly: false                    #Default parametre sadece okuabilir olmasını sağlar.
                                         #False parametresini aldığında kullanıcı dosyada okuma yazma yetkisine sahip olur.

- hosts: samba-client
  roles:
    - plusclouds.samba.client
    - plusclouds.samba.client.mount
  vars:
    - host_ip: 10.8.0.0                          #samba server ip'si
    - local_mount_path: /home/backup             #localde mount edilecek dizin
    - sharing_path_name: deneme1                 #samba server tarafından paylasıma acılan dizin
    - samba_user: "plusclouds"                   #samba server kullanıcı adı
    - samba_user_pass: "pass123"                 #samba server kullanıcı parolası
