- hosts: rabbitmq
  become: yes
  become_user: root
  roles:
    - { role: ntp, tags: [ 'ntp' ] }
    - { role: rabbitmq, tags: ['rabbitmq'] }
    - { role: beats, tags: [ 'beats' ] }
    - { role: datadog, tags: [ 'datadog'] }
    - { role: users, tags: [ 'users' ] }  
    - { role: clamav, tags: [ 'clamav' ] }
