---
- name: Epel Release
  yum:
    name: 'epel-release'
    state: installed

- name: Add Repository 'remi-repo'
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: install php7.3
  yum:
    name: "{{ item }}"
    enablerepo: epel,remi,remi-php73
    state: installed
  with_items: "{{ centos7_php_pkgs }}"
