---
- name: Start Apache Kafka server.
  shell: /usr/local/kafka_2.12-0.11.0.2/bin/kafka-server-start.sh /usr/local/kafka_2.12-0.11.0.2/config/server.properties
  async: 31536000 # Stay alive for a year(1 year = 31536000 seconds).
  poll: 0