---

- name: Add Zabbix Repository
  ansible.builtin.yum:
    deb: https://repo.zabbix.com/zabbix/6.0/debian/pool/main/z/zabbix-release/zabbix-release_6.0-5+debian12_all.deb
 
- name: Dist Upgrade
  ansible.builtin.yum:
    upgrade: dist
    update_cache: yes

- name: Install packages
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: 
    - zabbix-agent
  
- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: 
    - zabbix-agent
    
- name: Copy config zabbix-agentd.conf 
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent