---
- name: Check required variables
  fail: msg="Variable {{ item }} is not defined"
  when: item is not defined
  with_items: "{{ blitz_server_bilgileri }}"

- name: Debian zabbix-agent install 
  include_tasks: Debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: RHEL zabbix-agent install 
  include_tasks: CentOS.yml
  when: ansible_facts['os_family'] == "RHEL"

- name: Firewall configuration 
  include_tasks: applyfirewall.yml
  when: apply_firewall_rules

- name: Disk Monitoring
  include_tasks: diskmon.yml
  when: disk_performance_monitoring

- name: Galera Monitoring
  include_tasks: galeramon.yml
  when: galera_monitoring

- name: Nginx Monitoring
  include_tasks: diskmon.yml
  when: nginx_monitoring
   
- name: Mysql Monitoring
  include_tasks: mysqlmon.yml
  when: mysql_monitoring 

- name: Pdns Monitoring
  include_tasks: pdnsmon.yml
  when: powerdns_monitoring

- name: Add host to blitz server
  include_tasks: addhost.yml
  when: host_ekle